training:
  learning_rate: 0.001
  epochs: 2
  batch_size: 128
  loss_type: mse
  weights_dir: "weights/"
  eval_out_dir: "results/evaluation/"

data:
  train:
    mode: "train"
    start_date: "1979-01-01"
    end_date: "2005-12-31"
  val:
    mode: "val"
    start_date: "2006-01-01"
    end_date: "2010-12-31"
  test:
    mode: "test"
    start_date: "2011-01-01"
    end_date: "2020-12-31"
  common_kwargs:
    variables: ["z", "q", "u", "v", "t"]
    levels: [1000, 850, 700, 500]
    extent: [-10, 0, 29, 36]
    data_path:
      input: "data/predictors/er5_*.nc"
      target: "data/predictands/MSWP_1979_2014.nc"
    return_metadata: false

models:
  vit:
    emb_size: 128
    patch_size: 4
    num_layers: 4
    num_heads: 4
    dropout: 0.0
  unet:
    init_features: 64